### PR TITLE
Gui: reconfigure long_click action as "Set Rotation Center"

### PR DESCRIPTION
**Pull request by ceremcem**
Related to #94. 

Checklist:

- [x] Branch rebased on latest master `git pull --rebase upstream master`
- [ ] Unit tests confirmed to pass by running `./bin/FreeCAD --run-test 0`  (Not passing, but I *think* it's not related with this PR)
- [x] Commit message is [well-written](https://chris.beams.io/posts/git-commit/)
- [x] Commit message includes `issue #<id>` or `fixes #<id>` where `<id>` is the [associated MantisBT](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) issue id if one exists

### CODE REVIEW

**Comment by ceremcem** [comment]
Continuing from #94: 

Setting the center of rotation is something I frequently do while inspecting a model. The `H` key is super duper distracting to users like me because I'm using `Turkish F` keyboard layout, so the `H` key is in place of `O` key.

Please use the touchpad with right hand and try to press `O` key whenever you want to "focus" on something, you'll understand what I mean. 

This PR makes "setting center of rotation" super accessible.

**Comment by realthunder** [comment]
Yes, the long press setting rotation is nice. But the original behavior of bringing up context menu is also kinda handy, especially if one wants to mostly just use a touchscreen for navigation. How about adding a modifier, like CTRL long press to set the rotation center.

**Comment by ceremcem** [comment]
I totally forget about touch screens. Now it makes sense to open the context menu with long press. 

I think navigation shouldn't require both hands. Keyboard shortcut should be considered only as a "last resort" (maybe for complex intentions, like `T,D`). I don't know if anyone uses "Touchpad mode" in daily manner but I find it impossible to use for more than a minute.

Gesture style is very promising for default navigation style on a laptop with touchpad. However it lacks of setting the rotation center (without involving keyboard), hence the PR. (How can one use `H` key on an "only touchscreen device" anyways?) 

As Gesture style actually diverges in the way you mention on a hardware level, the long_press behavior selection might be done in a "persistent configuration level", probably through preferences or by using a shortcut to toggle it permanently or with a whole new navigation style menu item. What do you think? Maybe what I'm talking about is a "Touchpad-2 style".  

(Related forum thread: https://www.forum.freecadweb.org/viewtopic.php?f=8&t=55026)

**Comment by ceremcem** [comment]
Closing regarding to 60f2599. Thanks!

**Pull request closed without merging**
