### PR TITLE
Add snap packaging & GH workflow

### PR DESCRIPTION
**Pull request by ppd**
Like c87611ac, but with grade: stable

The same thing for LinkStage3.

### CODE REVIEW

**Comment by realthunder** [comment]
@ppd Just tried local build snap stable image, it somehow stuck at pulling gmsh source code. Ctrl+C has no effect. Any idea how to deal with this kind of situation?

**Comment by ppd** [comment]
Oh. I guess you could do multipass stop snapcraft-freecad-realthunder to kill the VM.

**Comment by ppd** [comment]
@luzpaz https://github.com/realthunder/FreeCAD/tree/2021.01.20-edge

The first revision is in the store: [freecad-realthunder](https://snapcraft.io/freecad-realthunder)

(although this is the PR for the stable channel)

**Comment by luzpaz** [comment]
@ppd amazing work!  
@realthunder where should we mention this option for snap packages (stable and edge)?

**Comment by realthunder** [comment]
@luzpaz I haven't trigged build for stable yet. Got a bit side tracked by other things last week. Once done, there would be options in snap web page for user to choose which version to install.

**Pull request merged**
