### PR TITLE
Add global commands to hide selected tree items, toggle show hidden tree items

### PR DESCRIPTION
**Pull request by scottmudge**
This adds global commands to hide selected (single or multiple) tree items, and to toggle whether or not hidden items are shown in the tree.

Currently the only way to do this is right clicking a tree item and selecting the menu item, and it only hides a single item at a time.

The default key bindings are:

* `Ctrl+Shift+H` to hide selected items
* `Ctrl+Shift+S` to toggle showing hidden items

The existing method of using the context/right-click menu is unchanged.

Also added are unique icons for these commands.

### CODE REVIEW

**Comment by realthunder** [comment]
I have squashed your commits into one [here](https://github.com/realthunder/FreeCAD/commit/5599dc19092b394d99902c21462b5c7ed1c64b99). Not sure why github didn't update the PR status here. Anyway, I've added two follow ups, to [change](https://github.com/realthunder/FreeCAD/commit/34a33634be557c76ed9ee1ea5aad27be484d3e94) the default shortcut `Ctrl+Shift+S` to `Shift+Alt+S` to avoid conflict with `Save as` command, and [change](https://github.com/realthunder/FreeCAD/commit/a6c4aa44a28cb497f1d9af1783dd0cd2279c2bbc) the command implementation to simpler property assignment.

**Comment by scottmudge** [comment]
Great, thanks! 

On an unrelated note, I've compiled OCC 7.6.0 w/ latest other libs (Boost 1.78, VTK 9.1, etc) for use with VS2022, but it looks like OCC 7.6.0 has done away with a lot of previously used headers. I saw you modified a couple files already, but for `OpenCascadeAll.h`, the following files no longer exist:

* `BRepAdaptor_HCurve.hxx`
* `BRepAdaptor_HCompCurve.hxx`
* `Geom2dAdaptor_HCurve.hxx`
* `Adaptor3d_HCurve.hxx`
* `Adaptor3d_HCurveOnSurface.hxx`
* `MMgt_TShared.hxx`
* `Quantity_Factor.hxx`
* `Quantity_Length.hxx`
* `Quantity_PlaneAngle.hxx`

I've added a similar compiler directive:

`# if OCC_VERSION_HEX < 0x070600 `

I've confirmed these files were removed in the official pre-compiled OCC release as well.

Maybe these headers were unused, but I have a feeling this is going to cause a lot of problems further down in compilation. I'm still fixing some Boost changes (some MSVC hacks for Boost -- `const unsigned options_description::m_default_line_length = 80;` in Application.cpp -- are no longer needed with dynamically linked Boost), but I'm guessing it's not going to compile fully.

**Comment by realthunder** [comment]
Yes indeed. I just merged a user proposed fix for some issue regarding build with OCC 7.6, but I only tested it on Linux. `OpenCasCadAll.h` is only used on Windows. I'll try on Windows soon.

**Comment by scottmudge** [comment]
Sounds good -- I will try and get it built and put any/all fixes required to do so on a new branch for your reference. I will close this PR since it seems like it's been appropriately merged in.

**Comment by scottmudge** [comment]
Okay, got the build working. Creating PR now.

**Pull request closed without merging**
