### PR TITLE
Dark mode improvements - text visibility

### PR DESCRIPTION
**Pull request by scottmudge**
The original thread for this issue can be found on the FreeCAD forum here:

https://forum.freecadweb.org/viewtopic.php?f=3&t=63882&p=548010#p548010

My primary issue was that the hard-coded green text in the TaskAttacher was difficult to read on Dark-mode stylesheets. In 0.20 it looks like a dark background box was added to help (it may no longer be needed, but it helps), however it was still difficult to read.

It didn't look like there was an easy way in the UI code for an arbitrary UI element to know whether or not a "Dark-mode" style was currently active. It was possible to get the stylesheet name, but that didn't confer forward compatibility should a dark stylesheet which *doesn't* have "dark" in the name be added.

I added a simple but effective method of detecting if a dark-mode style is active by comparing the value (brightness) of the default text color against the default background color. If the foreground text color is brighter than the background, it is assumed a dark-mode is active.

A state variable was added to `MainWindow` to keep track of this, along with a public method to return this state.  This state variable is updated anytime a stylesheet is set. This dark-mode state is accessed by TaskAttacher, which then uses "lightgreen" instead of the darker "green" color when the hard-coded stylesheet is set for the `QLabel` object.

The end result is this:

image

The text readability is improved for dark modes, while the light-mode color is unchanged.

### CODE REVIEW

**Review by realthunder — COMMENTED** [review]
I think this commit [968f57c](https://github.com/realthunder/FreeCAD/pull/209/commits/968f57c8ad1bf8d5c7789f8db5a87bc1e8968c4e) is better than the following one which relies on the main window palette, because it is perfectly fine to have a dark-ish main window while having a light-ish task view.

**Comment by scottmudge** [comment]
Indeed it was more adaptive to local color variation, but it did not produce the correct results when the TaskAttacher's `updatePreview()` was called *before* the TaskAttacher window was visible. For instance, clicking on a surface, then creating a DatumPlane, the TaskAttacher's `updatePreview()` was called *before* the TaskAttacher window was visible, so the existing palette used for the comparison operation was not initialized. It therefore always thought a "light" mode was active.

If the TaskAttacher window was *already* visible (click on DatumPlane button *before* clicking a surface), it's already had a chance to call `updatePreview()` once before the green text would need to be displayed.

I ended up using the MainWindow because it is visible from the start of the application.

I think it would probably be better to use the "Overlay Stylesheet" than the main stylesheet, since the Overlay Stylesheet appears to determine the background color of the TaskAttacher, at least it does when the Transparent mode is active, so that may be a compromise. 

I will try making that change now.

**Comment by scottmudge** [comment]
Actually, even when the Overlay `Light` or `Light-Outline` stylesheets are activated with a Dark stylesheet, the attachment pane label backgrounds are still dark:

image

So my latest commit using the MainWindow style still works fine, since it doesn't look like the "Light" overlay stylesheets affect the label backgrounds.

It's actually hard to read the label and button text when a dark-mode main stylesheet is active with a light-mode overlay stylesheet. Probably something that should be fixed. I can look into it.

**Comment by scottmudge** [comment]
However, when the overlay is turned off, the correct color is used again, even when the overlay stylesheet is still set to light:

image

I think the most reliable option is to use the MainWindow style palette, since the overlay stylesheet colors are only applied when the overlay mode is active (which many people don't use). 

In which instance would the task view be light while the main window be dark? I cannot seem to produce this configuration.

**Comment by scottmudge** [comment]
Nevermind, I see now -- when the "Darker" or "Dark" modes are active with a "Light" overlay mode, it becomes difficult to see:

image

Only "ProDark" does the dark backgrounds still persist in the Light mode overlay.

I will look for a solution.

**Comment by scottmudge** [comment]
Actually, this looks like another issue. When any of the following Style sheets are active while the "Light" overlay stylesheet is active, the labels and buttons become almost impossible to see:

* Behave-dark
* Dark-green/-blue/-contrast/-orange
* Darker-green/-blue/-orange
* Pro-dark

Eample:

image

It might be worth considering to **force** a dark overlay stylesheet (or set to "auto") when any of these main stylesheets are active. Or at least issue a warning messagebox.

**Comment by realthunder** [comment]
The simplest way I can see is actually to check for some button's `QPalette::WindowText`, e.g. `ui->buttonRef1`. If the value is less than 128, then it's dark text, or else light text. We can rely on the text color along.

This is actually quite a difficult problem to solve in a satisfying way. Ideally, we should make it either a `qproperty` or a preference setting for user to customize. The difficult part is how to come up with a sensible default setting while allow user to override. See some relevant discussion [here](https://github.com/realthunder/FreeCAD_assembly3/issues/787) and the associated PR #170, although I think the logic implemented there can still use some refinement.

**Comment by realthunder** [comment]
Please check commit 14062dcce9d6d9547d1b0364d87b485a166791d6, which I think should provide a more satisfying solution.

To summarize, the dark/light theme is auto detected based on the button text color as mentioned above. The color is rechecked in response to `QEvent::PaletteChange`. In addition, messageColor and errorColor are exposed to stylesheet as below,

```
PartGui--TaskAttacher {
    qproperty-messageColor : green;
    qproperty-errorColor : red;
} 
```

**Comment by scottmudge** [comment]
Great, that seems like a good implementation. Thanks for the changes!

**Pull request closed without merging**
