### PR TITLE
TaskAttacher: prevent autoNext from looping

### LINKED ISSUE #754: Attachment: Plane Selection Error
[infnite_shape.webm](https://user-images.githubusercontent.com/37031126/225889178-3f6b515e-2953-4909-98ec-51d745aa0fd2.webm)
This is test on the latest git clone

### PR DESCRIPTION
**Pull request by Nsikak1**
Thank you for creating a pull request to contribute to FreeCAD! To ease integration, we ask you to conform to the following items. Pull requests which don't satisfy all the items below might be rejected. If you are in doubt with any of the items below, don't hesitate to ask for help in the [FreeCAD forum](https://forum.freecadweb.org/viewforum.php?f=10)!

- [ x]  Your pull request is confined strictly to a single module. That is, all the files changed by your pull request are either in `App`, `Base`, `Gui` or one of the `Mod` subfolders. If you need to make changes in several locations, make several pull requests and wait for the first one to be merged before submitting the next ones
- [x ]  In case your pull request does more than just fixing small bugs, make sure you discussed your ideas with other developers on the FreeCAD forum
- [ x]  Your branch is [rebased](https://git-scm.com/docs/git-rebase) on latest master `git pull --rebase upstream master`
- [ x]  All FreeCAD unit tests are confirmed to pass by running `./bin/FreeCAD --run-test 0`
- [x ]  All commit messages are [well-written](https://chris.beams.io/posts/git-commit/) ex: `Fixes typo in Draft Move command text`
- [ x]  Your pull request is well written and has a good description, and its title starts with the module name, ex: `Draft: Fixed typos`
- [x ]  Commit messages include `issue #<id>` or `fixes #<id>` where `<id>` is the [FreeCAD bug tracker issue number](https://freecadweb.org/wiki/tracker#GitHub_and_MantisBT) in case a particular commit solves or is related to an existing issue on the tracker. Ex: `Draft: fix typos - fixes #0004805`

And please remember to update the Wiki with the features added or changed once this PR is merged.  
**Note**: If you don't have wiki access, then please mention your contribution on the [0.20 Changelog Forum Thread](https://forum.freecadweb.org/viewtopic.php?f=10&t=56135).

---
The Issue is when you select an attachment plane it automatically goes to the next selection  so if you wanted to select another plane it gives an infinite shape error, check issue   #754 for a video walk-through.
This Fixes temporally fixes  #754

### CODE REVIEW

**Comment by Nsikak1** [comment]
@realthunder

**Comment by realthunder** [comment]
I don't think this is an appropriate fix. There are attachment type requiring more than one element. The attacher task dialog tries to guess the attachment type based on the number of selections and the type of the selected element. Selecting two faces suggest a somewhat obscure attachment type called `Inertia 2-3`. I think a proper fix is either add an option to disable auto guess attachment type, or improve the guessing logic, e.g. do not use `Inertia 2-3` for infinite shape.

**Comment by Nsikak1** [comment]
Thank you, I knew it wasn't the right fix hence why i wrote 'temporary", although this is currently beyond by capability,
1. is it possible to detect it is a sketch attachment and replace the logic with a switch statement and break on detection so it exit(break);
2. can you attach a sketch to two plane?
Understanding the code was overwhelming and difficult is there a documentation somewhere?
Thank you for your time.

**Comment by Nsikak1** [comment]
Why i want to fix it is if you start a new document and want to create a sketch and you mistakenly choose the wrong plane a beginner wont be able to undo the problem.

**Pull request closed without merging**
