### PR TITLE
Fix more typos

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by luzpaz** [comment]
Question (unrelated to this PR): would you consider renaming `s/pathes/paths/`
There are places in your code that you utilize the parameter `pathes`. I was hoping we could have that parameter actually be correctly spelled.

**Comment by realthunder** [comment]
Yes, sure.

**Comment by luzpaz** [comment]
@realthunder actually nvm, looks like there would be a problem in `src/App/Expressions.cpp` because there is already a function that is called `paths` so it would conflict there.

**Comment by realthunder** [comment]
I didn't see any function named `paths`, just arguments. I've fixed typos now.

**Pull request merged**
